export default{
    ADD_NOTE: 'ADD_NOTE',
    REMOVE_NOTE: 'REMOVE_NOTE',
    UPDATE_NOTE: 'UPDATE_NOTE',

    SET_INPUT_TITLE: 'SET_INPUT_TITLE',
    SET_INPUT_CONTENT: 'SET_INPUT_CONTENT',
    RESET_INPUT: 'ESET_INPUT',
}