export default{
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',

    SET_INPUT_TITLE: 'SET_INPUT_TITLE',
    SET_INPUT_CONTENT: 'SET_INPUT_CONTENT',
    RESET_INPUT: 'ESET_INPUT',
}